// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package com.example.grpc.server.grpcserver.order;

public interface CreateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.order.CreateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.example.grpc.server.grpcserver.order.ProtoOrder order = 1;</code>
   */
  boolean hasOrder();
  /**
   * <code>.com.example.grpc.server.grpcserver.order.ProtoOrder order = 1;</code>
   */
  com.example.grpc.server.grpcserver.order.ProtoOrder getOrder();
  /**
   * <code>.com.example.grpc.server.grpcserver.order.ProtoOrder order = 1;</code>
   */
  com.example.grpc.server.grpcserver.order.ProtoOrderOrBuilder getOrderOrBuilder();
}
