// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package com.example.grpc.server.grpcserver.order;

public interface DeleteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.order.DeleteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string order_id = 1;</code>
   */
  java.lang.String getOrderId();
  /**
   * <code>string order_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getOrderIdBytes();
}
