// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: director.proto

package com.example.grpc.server.grpcserver.director;

public interface CreateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.director.CreateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.example.grpc.server.grpcserver.director.ProtoDirector director = 1;</code>
   */
  boolean hasDirector();
  /**
   * <code>.com.example.grpc.server.grpcserver.director.ProtoDirector director = 1;</code>
   */
  com.example.grpc.server.grpcserver.director.ProtoDirector getDirector();
  /**
   * <code>.com.example.grpc.server.grpcserver.director.ProtoDirector director = 1;</code>
   */
  com.example.grpc.server.grpcserver.director.ProtoDirectorOrBuilder getDirectorOrBuilder();
}
