// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: director.proto

package com.example.grpc.server.grpcserver.director;

public interface GetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.director.GetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string director_name = 1;</code>
   */
  java.lang.String getDirectorName();
  /**
   * <code>string director_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getDirectorNameBytes();
}
