// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package com.example.grpc.server.grpcserver.order;

public final class Order {
  private Order() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_server_grpcserver_order_ProtoOrder_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_server_grpcserver_order_ProtoOrder_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_server_grpcserver_order_GetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_server_grpcserver_order_GetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_server_grpcserver_order_GetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_server_grpcserver_order_GetResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_server_grpcserver_order_CreateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_server_grpcserver_order_CreateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_server_grpcserver_order_CreateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_server_grpcserver_order_CreateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_server_grpcserver_order_DeleteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_server_grpcserver_order_DeleteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpc_server_grpcserver_order_DeleteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpc_server_grpcserver_order_DeleteResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013order.proto\022(com.example.grpc.server.g" +
      "rpcserver.order\"Y\n\nProtoOrder\022\017\n\007request" +
      "\030\001 \001(\005\022\023\n\013customer_id\030\002 \001(\t\022\025\n\rdirector_" +
      "name\030\003 \001(\t\022\016\n\006status\030\004 \001(\t\"\036\n\nGetRequest" +
      "\022\020\n\010order_id\030\001 \001(\t\"\036\n\013GetResponse\022\017\n\007req" +
      "uest\030\001 \001(\005\"T\n\rCreateRequest\022C\n\005order\030\001 \001" +
      "(\01324.com.example.grpc.server.grpcserver." +
      "order.ProtoOrder\"\034\n\016CreateResponse\022\n\n\002id" +
      "\030\001 \001(\t\"!\n\rDeleteRequest\022\020\n\010order_id\030\001 \001(" +
      "\t\" \n\016DeleteResponse\022\016\n\006report\030\001 \001(\t2\374\002\n\014",
      "OrderService\022r\n\003get\0224.com.example.grpc.s" +
      "erver.grpcserver.order.GetRequest\0325.com." +
      "example.grpc.server.grpcserver.order.Get" +
      "Response\022{\n\006delete\0227.com.example.grpc.se" +
      "rver.grpcserver.order.DeleteRequest\0328.co" +
      "m.example.grpc.server.grpcserver.order.D" +
      "eleteResponse\022{\n\006create\0227.com.example.gr" +
      "pc.server.grpcserver.order.CreateRequest" +
      "\0328.com.example.grpc.server.grpcserver.or" +
      "der.CreateResponseB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_example_grpc_server_grpcserver_order_ProtoOrder_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_grpc_server_grpcserver_order_ProtoOrder_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_server_grpcserver_order_ProtoOrder_descriptor,
        new java.lang.String[] { "Request", "CustomerId", "DirectorName", "Status", });
    internal_static_com_example_grpc_server_grpcserver_order_GetRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_grpc_server_grpcserver_order_GetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_server_grpcserver_order_GetRequest_descriptor,
        new java.lang.String[] { "OrderId", });
    internal_static_com_example_grpc_server_grpcserver_order_GetResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_example_grpc_server_grpcserver_order_GetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_server_grpcserver_order_GetResponse_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_com_example_grpc_server_grpcserver_order_CreateRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_example_grpc_server_grpcserver_order_CreateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_server_grpcserver_order_CreateRequest_descriptor,
        new java.lang.String[] { "Order", });
    internal_static_com_example_grpc_server_grpcserver_order_CreateResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_example_grpc_server_grpcserver_order_CreateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_server_grpcserver_order_CreateResponse_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_example_grpc_server_grpcserver_order_DeleteRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_example_grpc_server_grpcserver_order_DeleteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_server_grpcserver_order_DeleteRequest_descriptor,
        new java.lang.String[] { "OrderId", });
    internal_static_com_example_grpc_server_grpcserver_order_DeleteResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_example_grpc_server_grpcserver_order_DeleteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpc_server_grpcserver_order_DeleteResponse_descriptor,
        new java.lang.String[] { "Report", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
