// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package com.example.grpc.server.grpcserver.order;

public interface ProtoOrderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.order.ProtoOrder)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 request = 1;</code>
   */
  int getRequest();

  /**
   * <code>string customer_id = 2;</code>
   */
  java.lang.String getCustomerId();
  /**
   * <code>string customer_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getCustomerIdBytes();

  /**
   * <code>string director_name = 3;</code>
   */
  java.lang.String getDirectorName();
  /**
   * <code>string director_name = 3;</code>
   */
  com.google.protobuf.ByteString
      getDirectorNameBytes();

  /**
   * <code>string status = 4;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 4;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
