// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customer.proto

package com.example.grpc.server.grpcserver.customer;

public interface CreateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.customer.CreateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.example.grpc.server.grpcserver.customer.ProtoCustomer customer = 1;</code>
   */
  boolean hasCustomer();
  /**
   * <code>.com.example.grpc.server.grpcserver.customer.ProtoCustomer customer = 1;</code>
   */
  com.example.grpc.server.grpcserver.customer.ProtoCustomer getCustomer();
  /**
   * <code>.com.example.grpc.server.grpcserver.customer.ProtoCustomer customer = 1;</code>
   */
  com.example.grpc.server.grpcserver.customer.ProtoCustomerOrBuilder getCustomerOrBuilder();
}
