// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customer.proto

package com.example.grpc.server.grpcserver.customer;

public interface GetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.customer.GetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string customer_id = 1;</code>
   */
  java.lang.String getCustomerId();
  /**
   * <code>string customer_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getCustomerIdBytes();
}
