// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customer.proto

package com.example.grpc.server.grpcserver.customer;

public interface ProtoCustomerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.customer.ProtoCustomer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 2;</code>
   */
  int getAge();

  /**
   * <code>int32 request = 3;</code>
   */
  int getRequest();
}
