// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: update.proto

package com.example.grpc.server.grpcserver.update;

public interface UpdateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.update.UpdateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string customer_id = 1;</code>
   */
  java.lang.String getCustomerId();
  /**
   * <code>string customer_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getCustomerIdBytes();

  /**
   * <code>string order_id = 2;</code>
   */
  java.lang.String getOrderId();
  /**
   * <code>string order_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getOrderIdBytes();
}
