// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: update.proto

package com.example.grpc.server.grpcserver.update;

public interface UpdateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.update.UpdateResponse)
    com.google.protobuf.MessageOrBuilder {
}
