// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customer.proto

package com.example.grpc.server.grpcserver.customer;

public interface GetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.server.grpcserver.customer.GetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 request = 1;</code>
   */
  int getRequest();
}
